### PR TITLE
Make Bundle Symfony 4 compatible and reduce compatibility to supported Versions

### PR DESCRIPTION
**Pull request by cedricziel**
This PR prepares the bundle for Symfony 4 and reduces the supported Symfony version range to the currently supported versions such as 3.4 (LTS) and 4.0 and up.

### CODE REVIEW

**Comment by cedricziel** [comment]
I'm not entirely sure what happens here: Is there anyone that could assist? It seems the selenium grid or the webdriver dies randomly *and* there's a failure with the cookies.

**Comment by Rikijs** [comment]
Hello!
Is there any progress made on this? I would like to upgrade to Symfony v4.1. but this bundle is keeping my project on Symfony v3.4... Sadly I can not help myself as i am not proficient in CI setups.

**Comment by nicodemuz** [comment]
When I try this branch with my Symfony4 app, I get the following error:

    egeloen/serializer-bundle 1.0.0 requires symfony/cache ^3.1 -> satisfiable by symfony/symfony[v3.4.12], symfony/cache[v3.1.0, v3.1.1, v3.1.10, v3.1.2, v3.1.3, v3.1.4, v3.1.5, v3.1.6, v3.1.7, v3.1.8, v3.1.9, v3.2.0, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.14, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.1, v3.3.10, v3.3.11, v3.3.12, v3.3.13, v3.3.14, v3.3.15, v3.3.16, v3.3.17, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9, v3.4.0, v3.4.1, v3.4.10, v3.4.11, v3.4.12, v3.4.2, v3.4.3, v3.4.4, v3.4.5, v3.4.6, v3.4.7, v3.4.8, v3.4.9]

**Comment by nicodemuz** [comment]
@cedricziel I don't think there's any cookie related functionality/code. Most likely the selenium server is not running.

Reference: https://github.com/FuckTheWorld/chromedriver/issues/728#issuecomment-328307568

**Comment by nicodemuz** [comment]
@cedricziel I think we need to avoid outputting selenium start script output to /dev/null (it might contain some clues):

https://github.com/egeloen/IvoryGoogleMapBundle/blob/28347e1f0d8c9d4b997c303c16186d8c6746a5a0/travis/install.sh#L26

**Pull request closed without merging**
