### PR TITLE
[3.0] Sync with egeloen/google-map library

### PR DESCRIPTION
**Pull request by egeloen**
This PR refactor the bundle in order to be in sync with the library.

### CODE REVIEW

**Comment by wesleylancel** [comment]
@egeloen Any reason why all options that were available in the `Configuration` class were removed?

**Comment by egeloen** [comment]
@wesleylancel Which options are your talking about exactly?

**Comment by wesleylancel** [comment]
@egeloen Being able to do stuff like this:

```
ivory_google_map:
    map:
        async: true
        auto_zoom: true
        width: "100%"
        height: "100%"
        map_options:
            scrollwheel: false
            mapTypeControl: false
    info_window:
        auto_close: true
```

**Comment by egeloen** [comment]
I see and I decided to remove these features because they involve too much code to maintain in the bundle and should leave in user land code.

In the past, this configuration would configure a factory (there were one factory by model objects...) which then would be used by the container when creating a new model objects (one service by model objects...).

Futhermore, it uses the container as a factory instead of as a container something I would like to fix from long time ago...

If you want to still benefit from a default configured map, create a factory in your code and rely on it when creating a map.

**Pull request merged**
