### PR TITLE
Added Version fix which allows any symfony version gte 3

### PR DESCRIPTION
**Pull request by Obermeijer**
Removes version lock and allows Symfony >= 3

### CODE REVIEW

**Comment by egeloen** [comment]
I'm a little bit confused with your PR. AFAIK, `^3.0` already allows any symfony 3.x versions while keeping BC whereas your constraint would allow any 3.x versions as well as 4.x, 5.x, ... (something we don't want at all for now as we don't know what Symfony will break in further major versions).

Can you clarify which bug do you encounter while submitting this PR?

**Comment by lastdreamer7591** [comment]
I can not install the bundle with composer with Symfony 3.2.1.
Maybe this pull-request solves the problem?

**Comment by JoydS** [comment]
Please, you need to make a new tag version. 
2.2.1 is "symfony/framework-bundle": "~2.1"

**Comment by Obermeijer** [comment]
Sorry for the late response due to the holidays. Happy new year btw :-)

I had this issue wrong, apparently when using  `composer require egeloen/google-map-bundle` it defers to version 2.2.1 which is indeed Symfony2 like JoydS said.

For Symfony3.x you'll have to specify the version when using composer require (`composer require egeloen/google-map-bundle master`) so this is indeed a matter of adding a new tag version.

**Comment by egeloen** [comment]
Ok, I see the issue now but unfortunatelly I'm not ready for the next major release... The master branch has major BC breaks and the next tag will not be a patch one but a major one (the 3.x one).

**Comment by Obermeijer** [comment]
Well I'm fine with the workaround for the moment. I'm using it with Symfony3.2 and it works fine.

For anyone else who has this issue, install the bundle using: `composer require egeloen/google-map-bundle master`.

Closing this pull, thanks for your time though!

**Pull request closed without merging**
